
version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: agrosphere
      POSTGRES_USER: agrosphere
      POSTGRES_PASSWORD: agrospherepwd
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 agrosphere.asgi:application
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
volumes:
  pgdata:
