
version: "3.9"
services:
  backend:
    build: ./backend
    working_dir: /usr/src/app
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/farmcap
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "5001:5000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    working_dir: /usr/src/app
    command: npm run start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=farmcap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
